[package]
name = "monome_rain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monome-rs = "1.1.3"
rand = "0.8.5"